### ISSUE TITLE
自实现代理协议与go代理协议的实现有差异

### ISSUE THREAD

**Issue by vodves-vodves** [baixudong007/gospider#3]
Doesn't work with resident proxies? It's just that if I run with regular proxies, everything works, but not with resident proxies.)

**Comment by baixudong007** [comment]
从报错信息来看，应该是远程主机主动关闭了连接导致的，事实上客户端已经与代理服务器建立连接了，代理服务器因为未知原因主动关闭了连接。  我有个疑问，这个代理在其他的客户端上是否能正常使用呢，如果在其他的客户端上也不能使用，是否意味着这个代理有问题

**Comment by vodves-vodves** [comment]
Everything works fine with the standard golang client

**Comment by baixudong007** [comment]
我大概已经知道出现这个问题的原因，这个问题我已经尝试在最新版修复它了，你现在可以更新模块，测试下这个问题是否被修复了

**Comment by vodves-vodves** [comment]
Nothing has changed) I can give you one resident proxy so you can test

**Comment by baixudong007** [comment]
好的，请将代理发送到 2216403312@qq.com 这个邮箱

**Comment by baixudong007** [comment]
当我的ip来源是亚洲地区时,使用你提供的代理出现如下报错：
```
Get "https://examplesite.com/": read tcp 192.168.1.239:51536->94.131.7.1:19001: wsarecv: An existing connection was forcibly closed by the remote host.
```
当我的ip来源是美国地区时,使用你提供的代理出现如下报错：
```
 Get "https://examplesite.com/": Unauthorized
```
我认为你提供的代理限制了使用者的ip地区。并且你给我提供的用户名密码存在错误，导致从而出现Unauthorized，以上问题当我使用golang 标准客户端也会出现。
