### ISSUE TITLE
Accept-Encoding的问题

### ISSUE THREAD

**Issue by eddylin83** [baixudong007/gospider#4]
最近get一个网站的时候发现出现403，查了一下，发现resp返回Vary是Accept-encoding。用检测发送头的网站看了一下，好像req里面的Accept-encoding只有gzip。而网站要求的是要带br。看了一下代码，默认的Accept-encoding是"gzip, deflate, br"，不知道为什么在https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending 检测只有gzip。操作系统是win10，是否跟安装的库有关？

**Comment by eddylin83** [comment]
嗯，主要是不熟悉golang的配置，把ClientOption的DisCompression设置为true就可以了。

**Comment by baixudong007** [comment]
gospider 的問題，Accept-encoding 拼写错误

**Comment by baixudong007** [comment]
已修复
