### ISSUE TITLE
不能在requests.ClientOption中设置Ja3Spec

### ISSUE THREAD

**Issue by jianmaikj** [baixudong007/gospider#6]
有时候需要动态Ja3，放在requests里面比较方便

**Comment by baixudong007** [comment]
之所以不放到requests 中是因为没有必要，如果放到requests 中，就会面临连接复用的问题，如果连接复用的话，那么在requests 中设置ja3将毫无意义。ja3的生效只会在tls 握手的时候才会产生，复用连接并不能保证这个连接的ja3和设置的ja3 相同。只有新建一个连接才能保证 设置的ja3 符合预期， 所以为了确保ja3的设置符合预期必须重新创建client ，故而没有必要在requests中设置ja3

**Comment by jianmaikj** [comment]
> requests.ClientOption 中设置ja3 应该参考文档 https://github.com/baixudong007/gospider/tree/master/requests#generate-fingerprint-from-string

好的 谢谢！
