### ISSUE TITLE
how install

### ISSUE THREAD

**Issue by mohghezal** [baixudong007/gospider#8]
can you build binary 
go build not work and
go get -u gitee.com/baixudong/gospider not work

**Comment by mohghezal** [comment]
root@kal-desktop:/home/kal# go get -u gitee.com/baixudong/gospider
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

**Comment by baixudong007** [comment]
> root@kal-desktop:/home/kal# go get -u gitee.com/baixudong/gospider go: go.mod file not found in current directory or any parent directory. 'go get' is no longer supported outside a module. To build and install a command, use 'go install' with a version, like 'go install example.com/cmd@latest' For more information, see https://golang.org/doc/go-get-install-deprecation or run 'go help get' or 'go help install'.

Are you a beginner in Golang? Please use GO mod to initialize your project
